const videos = [
    {
        id: "html-video",
        title: "آموزش HTML برای مبتدی‌ها",
        channel: "Mohammad Mahdi",
        subscribers: "125K subscribers",
        views: "120K views",
        date: "3 days ago",
        description: "در این ویدئو مبانی HTML را از صفر یاد می‌گیریم.",
        image: "https://picsum.photos/500/280?random=1",
        avatar: "M",
        duration: "12:45",
        category: "html",

        type: "youtube",
        src: "https://www.youtube-nocookie.com/embed/qz0aGYrrlhU"
    },

    {
        id: "css-flexbox",
        title: "CSS Flexbox به زبان ساده",
        channel: "Code Academy",
        subscribers: "80K subscribers",
        views: "85K views",
        date: "1 week ago",
        description: "در این آموزش با Flexbox آشنا می‌شویم.",
        image: "https://picsum.photos/500/280?random=2",
        avatar: "C",
        duration: "08:20",
        category: "css",

        type: "site",
        src: "https://www.w3schools.com/html/mov_bbb.mp4"
    },

    {
        id: "youtube-header",
        title: "طراحی هدر شبیه یوتیوب",
        channel: "Frontend Lab",
        subscribers: "42K subscribers",
        views: "42K views",
        date: "5 days ago",
        description: "در این ویدئو هدر یوتیوب‌کلون را می‌سازیم.",
        image: "https://picsum.photos/500/280?random=3",
        avatar: "F",
        duration: "15:10",
        category: "html",

        type: "youtube",
        src: "https://www.youtube-nocookie.com/embed/G3e-cpL7ofc"
    },
    
    {
        id: "youtube-clone-project",
        title: "پروژه تمرینی شبیه YouTube",
        channel: "Practice Channel",
        subscribers: "18K subscribers",
        views: "18K views",
        date: "6 days ago",
        description: "در این پروژه یک نسخهٔ تمرینی از یوتیوب طراحی می‌کنیم.",
        image: "https://picsum.photos/500/280?random=6",
        avatar: "P",
        duration: "06:50",
        category: "javascript",

        type: "site",
        src: ""
    },

    {
        id: "css-grid",
        title: "یادگیری Grid در CSS",
        channel: "Web Design Pro",
        subscribers: "91K subscribers",
        views: "90K views",
        date: "2 weeks ago",
        description: "در این آموزش CSS Grid را یاد می‌گیریم.",
        image: "https://picsum.photos/500/280?random=4",
        avatar: "W",
        duration: "10:05",
        category: "css",

        type: "site",
        src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
    },

    {
        id: "html-css-cards",
        title: "ساخت کارت‌های حرفه‌ای با HTML و CSS",
        channel: "Dev Master",
        subscribers: "67K subscribers",
        views: "67K views",
        date: "4 days ago",
        description: "در این ویدئو کارت‌های مدرن طراحی می‌کنیم.",
        image: "https://picsum.photos/500/280?random=5",
        avatar: "D",
        duration: "21:34",
        category: "css",

        type: "youtube",
        src: "https://noodlemagazine.com/watch/-131482780_456239095"
    },
   {
    id: "got-s01e01-720p",
    title: "Game of Thrones - Season 1 Episode 1",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 1 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E01.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e02-720p",
    title: "Game of Thrones - Season 1 Episode 2",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 2 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E02.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e03-720p",
    title: "Game of Thrones - Season 1 Episode 3",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 3 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E03.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e04-720p",
    title: "Game of Thrones - Season 1 Episode 4",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 4 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E04.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e05-720p",
    title: "Game of Thrones - Season 1 Episode 5",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 5 - 720p BluRay - SoftSub Persian",
    image: "images/my-photo.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E05.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e06-720p",
    title: "Game of Thrones - Season 1 Episode 6",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 6 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E06.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e07-720p",
    title: "Game of Thrones - Season 1 Episode 7",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 7 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E07.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e08-720p",
    title: "Game of Thrones - Season 1 Episode 8",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 8 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E08.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e09-720p",
    title: "Game of Thrones - Season 1 Episode 9",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 9 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E09.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},
{
    id: "got-s01e10-720p",
    title: "Game of Thrones - Season 1 Episode 10",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 1",
    description: "Game of Thrones Season 1 Episode 10 - 720p BluRay - SoftSub Persian",
    image: "images/gameofthrones.jpg",
    avatar: "G",
    duration: "55:00",
    category: "Game.of.Thrones.S01.720px",
    type: "site",
    src: "https://dls4.aparatchi-dlcenter.top/DonyayeSerial/series2/tt0944947/SoftSub/S01/720p.BluRay/Game.of.Thrones.S01E10.720p.BluRay.SoftSub.Unknown.DonyayeSerial.mkv"
},

{
    id: "monarch-s02e01-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 1",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 1 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E01.720p.Web-DL.x264.Pahe.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e02-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 2",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 2 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E02.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e03-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 3",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 3 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E03.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e04-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 4",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 4 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E04.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e05-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 5",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 5 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E05.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e06-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 6",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 6 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E06.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e07-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 7",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 7 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E07.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e08-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 8",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 8 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E08.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e09-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 9",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 9 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E09.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
},
{
    id: "monarch-s02e10-720p",
    title: "Monarch: Legacy of Monsters - Season 2 Episode 10",
    channel: "DonyayeSerial",
    subscribers: "—",
    views: "—",
    date: "Season 2",
    description: "Monarch: Legacy of Monsters Season 2 Episode 10 - 720p Web-DL - SoftSub Persian",
    image: "images/monarch.jpg",
    avatar: "M",
    duration: "50:00",
    category: "Monarch.Legacy.of.Monsters.S02.720p",
    type: "site",
    src: "https://dls6.aparatchi-dlcenter.top/DonyayeSerial/series4/tt17220216/SoftSub/S02/720p.Web-DL/Monarch.Legacy.of.Monsters.S02E10.720p.Web-DL.x264.SoftSub.DonyayeSerial.mkv"
}



]